# Generated by Django 3.2.4 on 2021-06-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210629_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(default='', help_text='Select a genre for this book', to='catalog.Genre'),
        ),
    ]
